<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>com.queryeer.backend</groupId>
        <artifactId>queryeer-backend</artifactId>
        <version>0.4.0</version>
        <relativePath>../pom.xml</relativePath>
    </parent>

    <artifactId>backend-lib-queryengine-jdbc-foundation</artifactId>
    <name>backend-lib-queryengine-jdbc-foundation</name>
    <properties>
        <queryeer.plugin.id>queryengine.runtime.jdbc-foundation</queryeer.plugin.id>
    </properties>

    <dependencies>
        <dependency>
            <groupId>com.queryeer.backend</groupId>
            <artifactId>backend-api</artifactId>
            <version>${project.version}</version>
            <scope>provided</scope>
        </dependency>

        <!-- TEST -->
        <dependency>
            <groupId>org.junit.jupiter</groupId>
            <artifactId>junit-jupiter</artifactId>
            <scope>test</scope>
        </dependency>
    </dependencies>
    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-dependency-plugin</artifactId>
                <executions>
                    <execution>
                        <id>write-queryeer-plugin-deps</id>
                        <phase>generate-resources</phase>
                        <goals>
                            <goal>build-classpath</goal>
                        </goals>
                        <configuration>
                            <includeScope>runtime</includeScope>
                            <outputFile>${project.build.directory}/queryeer-plugin-deps.txt</outputFile>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-assembly-plugin</artifactId>
                <configuration>
                    <descriptors>
                        <descriptor>${project.parent.basedir}/src/assembly/backend-plugin.xml</descriptor>
                    </descriptors>
                    <finalName>${queryeer.plugin.id}</finalName>
                    <appendAssemblyId>false</appendAssemblyId>
                </configuration>
                <executions>
                    <execution>
                        <id>assemble-queryeer-plugin</id>
                        <phase>package</phase>
                        <goals>
                            <goal>single</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>
</project>
