<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>com.queryeer.backend</groupId>
        <artifactId>queryeer-backend</artifactId>
        <version>0.13.1</version>
        <relativePath>../pom.xml</relativePath>
    </parent>
    <artifactId>backend-plugin-dialect-sqlserver</artifactId>
    <name>Queryeer SQL Server Dialect Plugin</name>

    <properties>
        <skipPublishing>true</skipPublishing>
        <queryeer.plugin.id>queryengine.jdbc.dialect.sqlserver</queryeer.plugin.id>
    </properties>

    <dependencies>
        <dependency>
            <groupId>com.queryeer.backend</groupId>
            <artifactId>backend-contract</artifactId>
            <version>${project.version}</version>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>com.queryeer.backend</groupId>
            <artifactId>backend-api</artifactId>
            <version>${project.version}</version>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>com.queryeer.backend</groupId>
            <artifactId>backend-lib-queryengine-jdbc-foundation</artifactId>
            <version>${project.version}</version>
            <scope>provided</scope>
        </dependency>

        <!-- TEST -->
        <dependency>
            <groupId>org.junit.jupiter</groupId>
            <artifactId>junit-jupiter</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.mockito</groupId>
            <artifactId>mockito-core</artifactId>
            <scope>test</scope>
        </dependency>
    </dependencies>
    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-dependency-plugin</artifactId>
                <executions>
                    <execution>
                        <id>write-queryeer-plugin-deps</id>
                        <phase>generate-resources</phase>
                        <goals>
                            <goal>build-classpath</goal>
                        </goals>
                        <configuration>
                            <includeScope>runtime</includeScope>
                            <outputFile>${project.build.directory}/queryeer-plugin-deps.txt</outputFile>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-assembly-plugin</artifactId>
                <configuration>
                    <descriptors>
                        <descriptor>${project.parent.basedir}/src/assembly/backend-plugin.xml</descriptor>
                    </descriptors>
                    <finalName>${queryeer.plugin.id}</finalName>
                    <appendAssemblyId>false</appendAssemblyId>
                </configuration>
                <executions>
                    <execution>
                        <id>assemble-queryeer-plugin</id>
                        <phase>package</phase>
                        <goals>
                            <goal>single</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>
    <!--
     <bind-api.version>4.0.2</bind-api.version>
     <jaxb-runtime.version>4.0.5</jaxb-runtime.version>

     <dependency>
        <groupId>jakarta.xml.bind</groupId>
        <artifactId>jakarta.xml.bind-api</artifactId>
        <version>${bind-api.version}</version>
    </dependency>
    <dependency>
        <groupId>org.glassfish.jaxb</groupId>
        <artifactId>jaxb-runtime</artifactId>
        <version>${jaxb-runtime.version}</version>
    </dependency>
    <build>
        <plugins>
            <plugin>
                <groupId>org.jvnet.jaxb</groupId>
                <artifactId>jaxb-maven-plugin</artifactId>
                <version>4.0.14</version>
                <executions>
                    <execution>
                        <goals>
                            <goal>generate</goal>
                        </goals>
                        <configuration>
                            <schemaDirectory>src/main/resources/xsd</schemaDirectory>
                            <generateDirectory>${project.build.directory}/generated-sources/xjc</generateDirectory>
                            <generatePackage>com.queryeer.backend.plugin.jdbc.sqlserver.showplan2019</generatePackage>
                            <schemaIncludes>
                                <include>/sqlserver2019queryplan.xsd</include>
                            </schemaIncludes>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>
    -->
</project>
