export enum MouseTargetType {
  UNKNOWN = 0,
  TEXTAREA = 1,
  GUTTER_GLYPH_MARGIN = 2,
  GUTTER_LINE_NUMBERS = 3,
  GUTTER_WHITESPACE = 4,
  CONTENT_TEXT = 5,
  CONTENT_EMPTY = 6,
  CONTENT_WIDGET = 7,
  OVERVIEW_GUTTER = 8,
  OVERLAY_WIDGET = 9,
  SCROLLBAR = 10,
  TEXTAREA_HANDLE = 11,
  OVERLAY_MASK = 12,
  OVERLAY = 13,
  BASE_CURSOR = 14,
  CARET = 15
}
